[typescript.type_mappings]
"Id" = "string"
"BigInt" = "string"
"BigDecimal" = "string"
"Bytes" = "string"
"Uuid" = "string"
"DateTime" = "string"
"Address" = "string"
"Url" = "string"
"U256" = "string"
