[target.wasm32-unknown-unknown]
# Required to make the rand feature of alloy work for wasm32-unknown-unknown
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[env]
# Limit test threads to avoid "too many open files" errors with mock servers
RUST_TEST_THREADS = "1"
