/*
 Generated by typeshare 1.7.0
*/

export interface OrderQueryVariables {
	id: string;
}

export interface Account {
	id: string;
}

export interface Erc20 {
	symbol: string;
}

export interface Transaction {
	block_number: bigint;
}

export interface TakeOrderEntity {
	id: string;
	sender: Account;
	input: bigint;
	input_display: string;
	input_token: Erc20;
	output: bigint;
	output_display: string;
	output_token: Erc20;
	ioratio: string;
	timestamp: bigint;
	transaction: Transaction;
}

export interface Order {
	id: string;
	owner: Account;
	interpreter: string;
	interpreter_store: string;
	expression_deployer: string;
	expression: string;
	timestamp: bigint;
	take_orders?: TakeOrderEntity[];
}

export interface OrderQuery {
	order?: Order;
}

