/*
 Generated by typeshare 1.7.0
*/

export type BigDecimalString = string;

export type BigIntString = string;

export type BytesString = string;

export interface OrderQueryVariables {
	id: string;
}

export interface Account {
	id: BytesString;
}

export interface Erc20 {
	symbol: string;
}

export interface Transaction {
	block_number: BigIntString;
}

export interface TakeOrderEntity {
	id: string;
	sender: Account;
	input: BigIntString;
	input_display: BigDecimalString;
	input_token: Erc20;
	output: BigIntString;
	output_display: BigDecimalString;
	output_token: Erc20;
	ioratio: BigDecimalString;
	timestamp: BigIntString;
	transaction: Transaction;
}

export interface Order {
	id: string;
	owner: Account;
	interpreter: BytesString;
	interpreter_store: BytesString;
	expression_deployer: BytesString;
	expression: BytesString;
	timestamp: BigIntString;
	take_orders?: TakeOrderEntity[];
}

export interface OrderQuery {
	order?: Order;
}

