/*
 Generated by typeshare 1.7.0
*/

export interface Account {
	id: string;
}

export interface Erc20 {
	name: string;
	symbol: string;
	decimals: number;
	total_supply: bigint;
	total_supply_display: string;
}

export interface TokenVault {
	id: string;
	balance_display: string;
	balance: bigint;
	token: Erc20;
}

export interface Vault {
	id: string;
	owner: Account;
	token_vaults?: TokenVault[];
}

export interface VaultsQuery {
	vaults: Vault[];
}

export enum VaultOrderBy {
	Id = "Id",
	VaultId = "VaultId",
	Owner = "Owner",
	OwnerId = "OwnerId",
	TokenVaults = "TokenVaults",
	Deposits = "Deposits",
	Withdraws = "Withdraws",
}

