/*
 Generated by typeshare 1.7.0
*/

export type BigDecimalString = string;

export type BigIntString = string;

export type BytesString = string;

export interface VaultQueryVariables {
	id: string;
}

export interface Account {
	id: BytesString;
}

export interface VaultDeposit {
	id: string;
	sender: Account;
	amount: BigIntString;
	amount_display: BigDecimalString;
}

export interface VaultWithdraw {
	id: string;
	sender: Account;
	amount: BigIntString;
	amount_display: BigDecimalString;
	requested_amount: BigIntString;
	requested_amount_display: BigDecimalString;
}

export interface Vault {
	id: string;
	owner: Account;
	deposits?: VaultDeposit[];
	withdraws?: VaultWithdraw[];
}

export interface VaultQuery {
	vault?: Vault;
}

