/*
 Generated by typeshare 1.7.0
*/

export interface VaultQueryVariables {
	id: string;
}

export interface Account {
	id: string;
}

export interface Erc20 {
	name: string;
	symbol: string;
	decimals: number;
}

export interface TokenVault {
	id: string;
	balance: bigint;
	balance_display: string;
	token: Erc20;
}

export interface VaultDeposit {
	id: string;
	sender: Account;
	amount: bigint;
	amount_display: string;
}

export interface VaultWithdraw {
	id: string;
	sender: Account;
	amount: bigint;
	amount_display: string;
	requested_amount: bigint;
	requested_amount_display: string;
}

export interface Vault {
	id: string;
	owner: Account;
	token_vaults?: TokenVault[];
	deposits?: VaultDeposit[];
	withdraws?: VaultWithdraw[];
}

export interface VaultQuery {
	vault?: Vault;
}

