/*
 Generated by typeshare 1.7.0
*/

export interface VaultQueryVariables {
	id: string;
}

export interface Account {
	id: string;
}

export interface VaultDeposit {
	id: string;
	sender: Account;
	amount: bigint;
	amount_display: string;
}

export interface VaultWithdraw {
	id: string;
	sender: Account;
	amount: bigint;
	amount_display: string;
	requested_amount: bigint;
	requested_amount_display: string;
}

export interface Vault {
	id: string;
	owner: Account;
	deposits?: VaultDeposit[];
	withdraws?: VaultWithdraw[];
}

export interface VaultQuery {
	vault?: Vault;
}

