[package]
name = "rain_orderbook_test_fixtures"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
rain_interpreter_test_fixtures = { path = "../../lib/rain.interpreter/crates/test_fixtures" }
rain-math-float.workspace = true
alloy = { workspace = true, features = [
    "node-bindings",
    "sol-types",
    "rpc-types",
    "provider-http",
    "network",
    "contract",
    "signer-local",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0", features = ["js", "js-sys"] }
