name: OrderBook Subgraph CI
on: [push]

jobs:
  subgraph-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Forge shallow install
        run: forge install --shallow

      - name: Start docker container
        run: docker-compose -f subgraph/docker/docker-compose.yaml up -d

      - name: Initialize setup
        working-directory: ./subgraph
        run: nix run .#init-setup

      - name: Install rustup stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install npm dependencies
        working-directory: ./subgraph
        run: npm install

      - name: Run test
        working-directory: ./subgraph
        run: nix run .#ci-test

      - name: Stop docker container
        run: docker-compose -f subgraph/docker/docker-compose.yaml down
