name: Tests

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Forge version
        run: forge --version
        id: forge-version

      - name: Forge install shallow
        run: forge install --shallow
        id: forge-install-shallow

      - name: git status
        run: git status
        id: git-status

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Prepare repo
        run: nix run

      - name: Run Forge tests
        run: forge test -vvv --gas-report
        id: test